using System.Collections;
using System.Collections.Generic;
using UnityEngine;

//왼쪽 끝으로 이동한 배경을 오른쪽 끝으로 재배치하는 스크립트
public class BackgroundLoop : MonoBehaviour
{
    private float width;//배경의 가로 길이

    private void Awake()
    {
        //가로길이를 측정하는 처리
        //BoxCollider2D 컴포넌트의 필드의 x 값을 가로 길이로 사용
        BoxCollider2D backgrounCollider = GetComponent<BoxCollider2D>();
        width = backgrounCollider.size.x;

            
    }

    private void Update()
    {
        //현제 위치가 원점에서 오른쪽으로 Width 이상 이동 했을 때 위치를 재배치
        if(transform.position.x <= -width)
        {
            Reposition();
        }
    }

    //위치를 재배치하는 메서드
    private void Reposition()
    {
        //현제 위치에서 오른쪽으로 가로 길이 *2만큼 이동
        Vector2 offse = new Vector2(width * 2f, 0);
        transform.position = (Vector2)transform.position + offse;
    }
}
